adobe/aepsdk-messaging-android

- .github/workflows/maven-release.yml
- .github/workflows/maven-snapshot.yml
- code/build.gradle
> updating workflows with dispatch

- Documentation/EdgeAndLaunchConfiguration.md
- Documentation/README.md
- Documentation/push/MessagingPushPayload.md
- README.md
- code/app/src/main/java/com/adobe/marketing/mobile/messagingsample/NotificationService.kt
- code/messaging/src/phone/java/com/adobe/marketing/mobile/MessagingPushPayload.java
- code/messaging/src/test/java/com/adobe/marketing/mobile/MessagingPushPayloadTests.java
- Renaming the `AEPMessagingFCMPushPayload` class to `MessagingPushPayload`
- Update Readme and documentation
> Renaming the AEPMessagingFCMPushPayload to MessagingPushPayload class

- Makefile
- code/messaging/build.gradle
> Updating gradle

- code/messaging/src/phone/java/com/adobe/marketing/mobile/MessagingInternal.java
> updating the log

- .github/workflows/maven-release.yml
- .github/workflows/maven-snapshot.yml
> updating github repos

- .github/workflows/maven-release.yml
- .github/workflows/maven-snapshot.yml
- code/messaging/src/phone/java/com/adobe/marketing/mobile/MessagingInternal.java
> Dev -> Staging

- code/app/build.gradle
- code/gradle.properties
- code/messaging/src/phone/java/com/adobe/marketing/mobile/MessagingConstant.java
- Releasing messaging sdk 1.0.0
> Releasing 1.0.0

- .github/workflows/functional-test.yml
> Add functional test workflow

- code/messaging/src/phone/java/com/adobe/marketing/mobile/InAppNotificationHandler.java
> Null check maps before looking for activity or placement id

- code/app/build.gradle
- code/messaging/src/main/AndroidManifest.xml
- code/messaging/src/phone/java/com/adobe/marketing/mobile/InAppNotificationHandler.java
> review updates

- code/app/src/main/java/com/adobe/marketing/mobile/messagingsample/MainActivity.kt
- code/messaging/src/phone/java/com/adobe/marketing/mobile/Message.java
- code/messaging/src/test/java/com/adobe/marketing/mobile/MessageTests.java
> fix corner radius extraction from mobile parameters

- code/app/build.gradle
- code/build.gradle
- code/gradle.properties
- code/messaging/src/androidTest/java/com/adobe/marketing/mobile/E2EFunctionalTests.java
- code/messaging/src/phone/java/com/adobe/marketing/mobile/MessagingConstants.java
Update the version to 1.2.0 as 1.1.0 will be used by the upcoming push notification release.
> Update IAM version to 1.2.0-beta-1

- code/app/build.gradle
- code/app/src/main/AndroidManifest.xml
- code/app/src/main/java/com/adobe/marketing/mobile/messagingsample/MainActivity.kt
- code/app/src/main/java/com/adobe/marketing/mobile/messagingsample/MessagingApplication.kt
- code/gradle.properties
- code/messaging/src/phone/java/com/adobe/marketing/mobile/IMessagingPushNotificationFactory.java
- code/messaging/src/phone/java/com/adobe/marketing/mobile/Messaging.java
- code/messaging/src/phone/java/com/adobe/marketing/mobile/MessagingConstants.java
- code/messaging/src/phone/java/com/adobe/marketing/mobile/MessagingInternal.java
- code/messaging/src/phone/java/com/adobe/marketing/mobile/MessagingPushInteractionHandler.java
- code/messaging/src/phone/java/com/adobe/marketing/mobile/MessagingPushNotificationFactory.java
- code/messaging/src/phone/java/com/adobe/marketing/mobile/MessagingPushNotificationHandler.java
- code/messaging/src/phone/java/com/adobe/marketing/mobile/MessagingPushPayload.java
- code/messaging/src/phone/java/com/adobe/marketing/mobile/MessagingPushReceiver.java
- code/messaging/src/phone/java/com/adobe/marketing/mobile/MessagingUtils.java
- code/messaging/src/test/java/com/adobe/marketing/mobile/MessagingDefaultImageDownloaderTests.java
- code/messaging/src/test/java/com/adobe/marketing/mobile/MessagingPushInteractionHandlerTests.java
- code/messaging/src/test/java/com/adobe/marketing/mobile/MessagingPushNotificationFactoryTests.java
- code/messaging/src/test/java/com/adobe/marketing/mobile/MessagingPushNotificationHandlerTests.java
- code/messaging/src/test/java/com/adobe/marketing/mobile/MessagingPushPayloadTests.java
- code/messaging/src/test/java/com/adobe/marketing/mobile/MessagingPushReceiverTests.java
- code/messaging/src/test/java/com/adobe/marketing/mobile/MessagingTestConstants.java
- code/messaging/src/test/java/com/adobe/marketing/mobile/MessagingTests.java
> Handle notification button presses + ajo push handling fixes

- code/messaging/src/phone/java/com/adobe/marketing/mobile/Messaging.java
> remove check  to determine if an aep push is received

- code/messaging/src/phone/java/com/adobe/marketing/mobile/MessagingConstant.java
- code/messaging/src/phone/java/com/adobe/marketing/mobile/MessagingPushPayload.java
- code/messaging/src/test/java/com/adobe/marketing/mobile/MessagingPushPayloadTests.java
- code/messaging/src/test/java/com/adobe/marketing/mobile/MessagingTests.java
- add ActionType.OPENAPP to the ActionType enum
> MessagingPushPayload updates: OPENAPP added to ActionType enum

- code/app/build.gradle
- code/gradle.properties
> Update dev version to 1.1.0

- code/app/build.gradle
- code/app/src/main/AndroidManifest.xml
- code/app/src/main/java/com/adobe/marketing/mobile/messagingsample/MainActivity.kt
- code/app/src/main/java/com/adobe/marketing/mobile/messagingsample/NotificationBroadcastReceiver.kt
- code/app/src/main/java/com/adobe/marketing/mobile/messagingsample/NotificationService.kt
- code/gradle.properties
- code/messaging/src/phone/java/com/adobe/marketing/mobile/MessagingConstant.java
- code/messaging/src/phone/java/com/adobe/marketing/mobile/MessagingPushPayload.java
- code/messaging/src/test/java/com/adobe/marketing/mobile/MessagingPushPayloadTests.java
- code/messaging/src/test/java/com/adobe/marketing/mobile/MessagingTests.java
> Merge Staging 1.1.0 to Main for 1.1.0 release

- .github/workflows/functional-test.yml
- Documentation/push/MessagingPushPayload.md
- code/app/build.gradle
- code/gradle.properties
- code/messaging/src/phone/java/com/adobe/marketing/mobile/MessagingConstant.java
- code/messaging/src/phone/java/com/adobe/marketing/mobile/MessagingPushPayload.java
- code/messaging/src/test/java/com/adobe/marketing/mobile/MessagingPushPayloadTests.java
> Handle  json exceptions when creating an action button

- .github/workflows/functional-test.yml
- Documentation/push/MessagingPushPayload.md
- code/app/build.gradle
- code/gradle.properties
- code/messaging/src/phone/java/com/adobe/marketing/mobile/MessagingConstant.java
- code/messaging/src/phone/java/com/adobe/marketing/mobile/MessagingPushPayload.java
- code/messaging/src/test/java/com/adobe/marketing/mobile/MessagingPushPayloadTests.java
> Dev to Staging-1.1.1 for 1.1.1 release

- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/MessageAssetDownloader.java
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/MessagingCacheUtilities.java
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/MessagingConstants.java
> Add support for cache service caching of proposition and image assets

- code/app/build.gradle
- code/app/src/main/AndroidManifest.xml
- code/build.gradle
- code/gradle/wrapper/gradle-wrapper.properties
- code/messaging/build.gradle
- code/messaging/src/main/AndroidManifest.xml
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/Message.java
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/MessageAssetDownloader.java
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/MessagingCacheUtilities.java
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/MessagingDelegate.java
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/MessagingExtension.java
- code/messaging/src/test/java/com/adobe/marketing/mobile/messaging/MessagingDelegateTests.java
- code/messaging/src/test/java/com/adobe/marketing/mobile/messaging/MessagingEdgeEventTypeTests.java
- code/messaging/src/test/java/com/adobe/marketing/mobile/messaging/MessagingExtensionHandleRulesResponseContentTests.java
- code/messaging/src/test/java/com/adobe/marketing/mobile/messaging/MessagingExtensionTests.java
- code/messaging/src/test/java/com/adobe/marketing/mobile/messaging/MessagingPushPayloadTests.java
- code/messaging/src/test/java/com/adobe/marketing/mobile/messaging/MessagingUtilsTests.java
- code/messaging/src/test/java/com/adobe/marketing/mobile/messaging/PropositionPayloadCachingTests.java
- code/messagingtestutils/build.gradle
- code/messagingtestutils/src/main/AndroidManifest.xml
- code/messagingtestutils/src/main/java/com/adobe/marketing/mobile/messaging/MessagingTestConstants.java
> test progress

- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/InAppNotificationHandler.java
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/ItemData.java
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/MessageAssetDownloader.java
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/MessagingExtension.java
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/MessagingUtils.java
- code/messaging/src/phone/java/com/adobe/marketing/mobile/Messaging.java
- code/messaging/src/test/java/com/adobe/marketing/mobile/messaging/MessagingExtensionTests.java
- code/messaging/src/test/java/com/adobe/marketing/mobile/messaging/MessagingUtilsTests.java
- also included a couple of test updates to verify the code changes
> Additional fixes based on @prudrabhat's reviews

- .circleci/config.yml
> Dev v2.0.0 to Staging v2.0.0 - updated circleci config

- code/gradle.properties
> fix module aar name

- .github/workflows/maven-release.yml
- .github/workflows/maven-snapshot.yml
> update java version is maven workflows

- .github/workflows/maven-release.yml
- .github/workflows/maven-snapshot.yml
- code/gradle.properties
> Dev v2.0.0 to Staging v2.0.0 - update java version in maven git workflows

- code/messaging/src/phone/java/com/adobe/marketing/mobile/Messaging.java
- also removed Nullable annotation from a primitive type (boolean)
> add NonNull annotation to extensionVersion api

- code/app/src/main/java/com/adobe/marketing/mobile/messagingsample/MainActivity.kt
- code/app/src/main/java/com/adobe/marketing/mobile/messagingsample/MessagingApplication.kt
- code/gradle.properties
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/internal/InAppNotificationHandler.java
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/internal/InternalMessage.java
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/internal/MessageAssetDownloader.java
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/internal/MessagingCacheUtilities.java
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/internal/MessagingConstants.java
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/internal/MessagingExtension.java
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/internal/MessagingFullscreenMessageDelegate.java
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/internal/MessagingUtils.java
- code/messaging/src/phone/java/com/adobe/marketing/mobile/Messaging.java
- code/messaging/src/test/java/com/adobe/marketing/mobile/messaging/internal/ImageAssetCachingTests.java
- code/messaging/src/test/java/com/adobe/marketing/mobile/messaging/internal/InAppNotificationHandlerTests.java
- code/messaging/src/test/java/com/adobe/marketing/mobile/messaging/internal/InternalMessageTests.java
- code/messaging/src/test/java/com/adobe/marketing/mobile/messaging/internal/MessageAssetDownloaderTests.java
- code/messaging/src/test/java/com/adobe/marketing/mobile/messaging/internal/MessagingFullscreenMessageDelegateTests.java
- code/messaging/src/test/java/com/adobe/marketing/mobile/messaging/internal/PropositionPayloadCachingTests.java
- code/messagingtestutils/build.gradle
- code/messagingtestutils/src/main/java/com/adobe/marketing/mobile/messaging/internal/MessageTestConfig.java
- code/messagingtestutils/src/main/java/com/adobe/marketing/mobile/messaging/internal/MessagingTestUtils.java
- update to core 2.0.1, fixes based on this core update
- unit tests fixes + updates
- fix creation of asset map containing asset url and cache location
- also fix handling of assurance generated IAM https://github.com/adobe/aepsdk-messaging-android/issues/134
> Updates for Messaging 2.0.1 release

- code/app/src/main/java/com/adobe/marketing/mobile/messagingsample/MainActivity.kt
- code/app/src/main/java/com/adobe/marketing/mobile/messagingsample/MessagingApplication.kt
- code/gradle.properties
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/internal/InternalMessage.java
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/internal/MessageAssetDownloader.java
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/internal/MessagingCacheUtilities.java
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/internal/MessagingConstants.java
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/internal/MessagingExtension.java
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/internal/MessagingFullscreenMessageDelegate.java
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/internal/MessagingUtils.java
- code/messaging/src/phone/java/com/adobe/marketing/mobile/Messaging.java
- code/messaging/src/test/java/com/adobe/marketing/mobile/messaging/internal/ImageAssetCachingTests.java
- code/messaging/src/test/java/com/adobe/marketing/mobile/messaging/internal/InAppNotificationHandlerTests.java
- code/messaging/src/test/java/com/adobe/marketing/mobile/messaging/internal/InternalMessageTests.java
- code/messaging/src/test/java/com/adobe/marketing/mobile/messaging/internal/MessageAssetDownloaderTests.java
- code/messaging/src/test/java/com/adobe/marketing/mobile/messaging/internal/MessagingFullscreenMessageDelegateTests.java
- code/messaging/src/test/java/com/adobe/marketing/mobile/messaging/internal/PropositionPayloadCachingTests.java
- code/messagingtestutils/build.gradle
- code/messagingtestutils/src/main/java/com/adobe/marketing/mobile/messaging/internal/MessageTestConfig.java
- code/messagingtestutils/src/main/java/com/adobe/marketing/mobile/messaging/internal/MessagingTestUtils.java
> Staging to main for 2.0.1 release

- code/app/src/main/java/com/adobe/marketing/mobile/messagingsample/MainActivity.kt
- code/app/src/main/res/layout/activity_main.xml
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/internal/InAppNotificationHandler.java
- code/messaging/src/test/java/com/adobe/marketing/mobile/messaging/internal/InAppNotificationHandlerTests.java
- correctly replace all found rules rather than just the first found rule
- also update test app to allow triggering a in-app message via a custom string
> Fix rule replacement

- code/gradle.properties
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/internal/MessagingConstants.java
- code/messaging/src/phone/java/com/adobe/marketing/mobile/Messaging.java
- also update constant value for REFRESH_MESSAGES_EVENT to "Retrieve message definitions"
> bump version to 2.0.2

- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/internal/InAppNotificationHandler.java
- code/messaging/src/test/java/com/adobe/marketing/mobile/messaging/internal/InAppNotificationHandlerTests.java
> Clear loaded rules when an empty payload is received from AJO

- code/gradle.properties
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/internal/MessagingConstants.java
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/internal/MessagingFullscreenMessageDelegate.java
- code/messaging/src/phone/java/com/adobe/marketing/mobile/Messaging.java
- code/messaging/src/test/java/com/adobe/marketing/mobile/messaging/internal/MessagingFullscreenMessageDelegateTests.java
The previous check for url validity was rejecting deeplinks. Removing this check as it will still be done within uiService.showUrl().
> do not validate url to allow use of any deeplink

- code/app/src/main/java/com/adobe/marketing/mobile/messagingsample/MainActivity.kt
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/internal/MessagingConstants.java
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/internal/MessagingFullscreenMessageDelegate.java
- code/messaging/src/test/java/com/adobe/marketing/mobile/messaging/internal/MessagingFullscreenMessageDelegateTests.java
> Fix deeplink processing

- code/gradle.properties
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/internal/MessagingConstants.java
- code/messaging/src/phone/java/com/adobe/marketing/mobile/Messaging.java
> bump version to 2.1.0

- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/internal/MessagingConstants.java
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/internal/MessagingFullscreenMessageDelegate.java
- code/messaging/src/test/java/com/adobe/marketing/mobile/messaging/internal/MessagingFullscreenMessageDelegateTests.java
- the link passed to overrideUrlLoad is already html unescaped
> remove html unescape code

- code/app/build.gradle
- code/app/src/main/java/com/adobe/inapp/bugbash/MessagingApplication.kt
> Enable multidex support in bug bash app

- code/app/src/main/java/com/adobe/inapp/bugbash/MessagingApplication.kt
Lifecycle extension required for application launch event content rendering
> add lifecycle extension to repair app launch issue

- code/app/src/main/AndroidManifest.xml
> Add deeplink schema to Android Manifest

- code/app/src/main/AndroidManifest.xml
- code/app/src/main/java/com/adobe/marketing/mobile/messagingsample/MainActivity.kt
Required behavior changes for Android 33 https://developer.android.com/develop/ui/views/notifications/notification-permission#best-practices
> Add notification permission in sample app

- code/app/src/main/res/layout/activity_main.xml
- code/gradle.properties
- code/messaging/src/androidTest/java/com/adobe/marketing/mobile/messaging/internal/MessageCachingFunctionalTests.java
- code/messaging/src/main/java/com/adobe/marketing/mobile/MessagingPushPayload.java
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/internal/InAppNotificationHandler.java
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/internal/InternalMessage.java
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/internal/ItemData.java
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/internal/MessagingCacheUtilities.java
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/internal/MessagingConstants.java
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/internal/MessagingExtension.java
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/internal/MessagingUtils.java
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/internal/PayloadItem.java
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/internal/PropositionInfo.java
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/internal/PropositionPayload.java
- code/messaging/src/phone/java/com/adobe/marketing/mobile/Messaging.java
- code/messaging/src/test/java/com/adobe/marketing/mobile/MessagingPushPayloadTests.java
- code/messaging/src/test/java/com/adobe/marketing/mobile/messaging/internal/ImageAssetCachingTests.java
- code/messaging/src/test/java/com/adobe/marketing/mobile/messaging/internal/InAppNotificationHandlerTests.java
- code/messaging/src/test/java/com/adobe/marketing/mobile/messaging/internal/InternalMessageTests.java
- code/messaging/src/test/java/com/adobe/marketing/mobile/messaging/internal/MessagingExtensionTests.java
- code/messaging/src/test/java/com/adobe/marketing/mobile/messaging/internal/PropositionPayloadCachingTests.java
- code/messaging/src/test/java/com/adobe/marketing/mobile/messaging/internal/PropositionPayloadTests.java
- code/messagingtestutils/src/main/java/com/adobe/marketing/mobile/messaging/internal/MessagingTestUtils.java
> better handling of multiple handles being returned in personalization:decisions responses

- code/messaging/src/main/java/com/adobe/marketing/mobile/Feed.java
- code/messaging/src/test/java/com/adobe/marketing/mobile/FeedItemTests.java
- code/messaging/src/test/java/com/adobe/marketing/mobile/FeedTests.java
> Add Feed class

- Documentation/sources/class-message.md
- Documentation/sources/how-to-messaging-delegate.md
- code/gradle.properties
- code/messaging/build.gradle
- code/messaging/src/androidTest/java/com/adobe/marketing/mobile/messaging/internal/MessagingPublicAPITests.java
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/internal/MessagingConstants.java
- code/messaging/src/phone/java/com/adobe/marketing/mobile/Messaging.java
- code/messaging/src/test/java/com/adobe/marketing/mobile/MessagingTests.java
- code/messaging/src/test/java/com/adobe/marketing/mobile/messaging/internal/MessagingExtensionTests.java
> Fix refreshInAppMessages api, update tests, fix messaging docs, update pom generation

- code/gradle.properties
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/internal/MessagingConstants.java
- code/messaging/src/phone/java/com/adobe/marketing/mobile/Messaging.java
> bump version to 2.1.3

- code/gradle.properties
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/internal/MessagingConstants.java
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/internal/MessagingFullscreenMessageDelegate.java
- code/messaging/src/phone/java/com/adobe/marketing/mobile/Messaging.java
- code/messaging/src/test/java/com/adobe/marketing/mobile/messaging/internal/MessagingFullscreenMessageDelegateTests.java
- Handle the new backPressed API MessagingDelegate API
- Send back button interaction event
- Send dismiss interaction event when the message is dismissed
interaction event when back button pressed
interaction event when action is done on IAM
> [MOB-18907] - Handle back button press interaction + tests

- .circleci/config.yml
- Makefile
- code/checkstyle.xml
- code/messaging/build.gradle
- code/messaging/checkstyle.gradle
- code/messaging/src/main/java/com/adobe/marketing/mobile/MessagingPushPayload.java
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/internal/InAppNotificationHandler.java
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/internal/InternalMessage.java
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/internal/MessagingConstants.java
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/internal/MessagingExtension.java
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/internal/MessagingFullscreenMessageDelegate.java
- code/messaging/src/phone/java/com/adobe/marketing/mobile/Messaging.java
- code/messaging/src/test/java/com/adobe/marketing/mobile/messaging/internal/MessagingExtensionTests.java
- code/messaging/src/test/java/com/adobe/marketing/mobile/messaging/internal/MessagingFullscreenMessageDelegateTests.java
- update messaging extension to use refactored LaunchRulesEngine
- add checkstyle functionality and fix style errors
> messaging extension updates

- code/messaging/src/main/java/com/adobe/marketing/mobile/InboundType.java
- code/messaging/src/main/java/com/adobe/marketing/mobile/Proposition.java
- code/messaging/src/main/java/com/adobe/marketing/mobile/PropositionItem.java
- code/messaging/src/main/java/com/adobe/marketing/mobile/Surface.java
- code/messaging/src/test/java/com/adobe/marketing/mobile/FeedItemTests.java
- code/messaging/src/test/java/com/adobe/marketing/mobile/FeedTests.java
- code/messaging/src/test/java/com/adobe/marketing/mobile/InboundTypeTests.java
- code/messaging/src/test/java/com/adobe/marketing/mobile/PropositionEventTypeTests.java
- code/messaging/src/test/java/com/adobe/marketing/mobile/PropositionItemTests.java
- code/messaging/src/test/java/com/adobe/marketing/mobile/PropositionTests.java
- code/messaging/src/test/java/com/adobe/marketing/mobile/SurfaceTests.java
- code/messaging/src/test/resources/proposition_item.json
- code/messagingtestutils/src/main/java/com/adobe/marketing/mobile/messaging/internal/MessagingTestConstants.java
- code/messagingtestutils/src/main/java/com/adobe/marketing/mobile/messaging/internal/MessagingTestUtils.java
> custom classes unit tests + add Proposition and PropositionItem creation from event data

- code/messaging/src/androidTest/java/com/adobe/marketing/mobile/messaging/internal/MessagingPublicAPITests.java
- code/messaging/src/main/java/com/adobe/marketing/mobile/Surface.java
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/internal/EdgePersonalizationResponseHandler.java
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/internal/MessagingConstants.java
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/internal/MessagingExtension.java
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/internal/MessagingUtils.java
- code/messaging/src/phone/java/com/adobe/marketing/mobile/Messaging.java
- code/messaging/src/test/java/com/adobe/marketing/mobile/FeedTests.java
- code/messaging/src/test/java/com/adobe/marketing/mobile/MessagingTests.java
- code/messaging/src/test/java/com/adobe/marketing/mobile/SurfaceTests.java
- code/messaging/src/test/java/com/adobe/marketing/mobile/messaging/internal/EdgePersonalizationResponseHandlerTests.java
- code/messaging/src/test/java/com/adobe/marketing/mobile/messaging/internal/MessagingExtensionTests.java
- code/messagingtestutils/src/main/java/com/adobe/marketing/mobile/messaging/internal/MessagingTestConstants.java
- code/messagingtestutils/src/main/java/com/adobe/marketing/mobile/messaging/internal/MessagingTestUtils.java
> [MOB-19239] Update feed retrieval from remote

- code/gradle.properties
- code/messaging/src/androidTest/java/com/adobe/marketing/mobile/messaging/internal/MessageCachingFunctionalTests.java
- code/messaging/src/main/java/com/adobe/marketing/mobile/Feed.java
- code/messaging/src/main/java/com/adobe/marketing/mobile/FeedItem.java
- code/messaging/src/main/java/com/adobe/marketing/mobile/Inbound.java
- code/messaging/src/main/java/com/adobe/marketing/mobile/InboundType.java
- code/messaging/src/main/java/com/adobe/marketing/mobile/Proposition.java
- code/messaging/src/main/java/com/adobe/marketing/mobile/PropositionItem.java
- code/messaging/src/main/java/com/adobe/marketing/mobile/Surface.java
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/internal/EdgePersonalizationResponseHandler.java
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/internal/FeedRulesEngine.java
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/internal/InternalMessage.java
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/internal/MessagingCacheUtilities.java
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/internal/MessagingConstants.java
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/internal/MessagingExtension.java
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/internal/MessagingUtils.java
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/internal/PropositionInfo.java
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/internal/PropositionPayload.java
- code/messaging/src/test/java/com/adobe/marketing/mobile/FeedTests.java
- code/messaging/src/test/java/com/adobe/marketing/mobile/InboundTypeTests.java
- code/messaging/src/test/java/com/adobe/marketing/mobile/PropositionItemTests.java
- code/messaging/src/test/java/com/adobe/marketing/mobile/PropositionTests.java
- code/messaging/src/test/java/com/adobe/marketing/mobile/messaging/internal/EdgePersonalizationResponseHandlerTests.java
- code/messaging/src/test/java/com/adobe/marketing/mobile/messaging/internal/InternalMessageTests.java
- code/messaging/src/test/java/com/adobe/marketing/mobile/messaging/internal/MessagingExtensionTests.java
- code/messaging/src/test/java/com/adobe/marketing/mobile/messaging/internal/PropositionPayloadCachingTests.java
- code/messaging/src/test/java/com/adobe/marketing/mobile/messaging/internal/PropositionPayloadTests.java
- code/messaging/src/test/resources/personalization_payload.json
- code/messagingtestutils/src/main/java/com/adobe/marketing/mobile/messaging/internal/MessagingTestUtils.java
> [MOB-19240] Implement internal handling of inbound content from Edge

- code/messaging/src/main/java/com/adobe/marketing/mobile/MessagingPushPayload.java
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/MessagingPushBuilder.java
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/internal/MessagingConstants.java
> Reading visibility from AJO Notifications

- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/MessagingPushBuilder.java
> Fix wrong Constant warning

- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/MessagingPushBuilder.java
> Push notification builder sets visibility correctly

- code/app/src/main/java/com/adobe/marketing/mobile/messagingsample/CodeBasedExperienceActivity.kt
- code/app/src/main/java/com/adobe/marketing/mobile/messagingsample/MainActivity.kt
- code/app/src/main/java/com/adobe/marketing/mobile/messagingsample/MessagingApplication.kt
- code/app/src/main/java/com/adobe/marketing/mobile/messagingsample/ScrollingFeedActivity.kt
- code/app/src/main/java/com/adobe/marketing/mobile/messagingsample/SingleFeedActivity.kt
> clean test app for cbe beta

- code/messaging/src/phone/java/com/adobe/marketing/mobile/Messaging.java
> remove unneeded suppress lint tags in Messaging.java

- code/app/src/main/java/com/adobe/marketing/mobile/messagingsample/CodeBasedExperienceActivity.kt
- code/app/src/main/java/com/adobe/marketing/mobile/messagingsample/MessagingApplication.kt
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/FeedRulesEngine.java
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/ParsedPropositions.java
- code/messaging/src/test/java/com/adobe/marketing/mobile/messaging/FeedRulesEngineTests.java
- code/messaging/src/test/java/com/adobe/marketing/mobile/messaging/MessagingUtilsTests.java
- code/messaging/src/test/java/com/adobe/marketing/mobile/messaging/ParsedPropositionsTests.java
- code/messaging/src/test/java/com/adobe/marketing/mobile/messaging/SurfaceTests.java
- code/messaging/src/test/resources/codeBasedPropositionContent.json
- code/messaging/src/test/resources/feedPropositionContent.json
- code/messaging/src/test/resources/feedPropositionContentFeedItemConsequences.json
- code/messaging/src/test/resources/inappPropositionV1Content.json
- code/messaging/src/test/resources/inappPropositionV2Content.json
- code/messaging/src/test/resources/ruleWithNoConsequence.json
- code/messaging/src/test/resources/ruleWithUnknownConsequenceSchema.json
> ParsedPropositions unit tests

- code/gradle.properties
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/internal/MessagingConstants.java
- code/messaging/src/phone/java/com/adobe/marketing/mobile/Messaging.java
> bump version to 2.2.1

- code/gradle.properties
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/MessagingPushBuilder.java
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/internal/MessageAssetDownloader.java
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/internal/MessagingConstants.java
- code/messaging/src/phone/java/com/adobe/marketing/mobile/Messaging.java
- Handle a null network connection exception which was causing the Messaging extension to fail to be registered.
> Dev v2.2.1 to staging for 2.2.1 release

- code/messaging/build.gradle.kts
> change namespace to avoid conflict

- code/gradle.properties
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/InternalMessagingUtils.java
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/MessagingConstants.java
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/MessagingExtension.java
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/Proposition.java
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/PropositionItem.java
- code/messaging/src/phone/java/com/adobe/marketing/mobile/Messaging.java
- code/messaging/src/test/java/com/adobe/marketing/mobile/messaging/InternalMessagingUtilsTests.java
- code/messaging/src/test/java/com/adobe/marketing/mobile/messaging/MessagingCacheUtilitiesTests.java
- code/messaging/src/test/java/com/adobe/marketing/mobile/messaging/MessagingUtilsTests.java
- code/messaging/src/test/java/com/adobe/marketing/mobile/messaging/PropositionInfoTests.java
- code/messaging/src/test/java/com/adobe/marketing/mobile/messaging/PropositionItemTests.java
- code/messaging/src/test/java/com/adobe/marketing/mobile/messaging/PropositionTests.java
- code/testapp/build.gradle.kts
> Handle debug event for in-app schema consequence

- Documentation/sources/api-usage.md
- Documentation/sources/enum-public-classes/class-message.md
- Documentation/sources/enum-public-classes/enum-messaging-edge-event-type.md
> Update the MessagingEdgeEventType documentation, cleanup Message interface docs

- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/EdgePersonalizationResponseHandler.java
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/PropositionItem.java
- code/messaging/src/test/java/com/adobe/marketing/mobile/messaging/EdgePersonalizationResponseHandlerTests.java
- code/messagingtestutils/src/main/java/com/adobe/marketing/mobile/messaging/MessagingTestUtils.java
- code/testapp/src/main/java/com/adobe/marketing/mobile/messagingsample/MessagingApplication.kt
> Reverse the order of in-app message rules before loading them in the rules engine

- code/testapp/src/main/java/com/adobe/marketing/mobile/messagingsample/FeedCardAdapter.kt
- code/testapp/src/main/java/com/adobe/marketing/mobile/messagingsample/ImageDownloader.kt
- code/testapp/src/main/java/com/adobe/marketing/mobile/messagingsample/SingleFeedActivity.kt
> change messaging test app to be compatible with new content card data

- code/messaging/src/androidTest/java/com/adobe/marketing/mobile/messaging/E2EFunctionalTests.java
> Add more e2e test error logging

- .circleci/config.yml
- .github/workflows/functional-test.yml
- code/messaging/src/androidTest/java/com/adobe/marketing/mobile/messaging/E2EFunctionalTests.java
> Take the latest functional test updates from main

- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/EdgePersonalizationResponseHandler.java
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/InternalMessagingUtils.java
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/MessagingExtension.java
- code/messaging/src/test/java/com/adobe/marketing/mobile/messaging/EdgePersonalizationResponseHandlerTests.java
- code/messaging/src/test/java/com/adobe/marketing/mobile/messaging/MessagingExtensionTests.java
- code/messagingtestutils/src/main/java/com/adobe/marketing/mobile/messaging/MessagingTestUtils.java
> Remove disqualified content cards from the in-memory cache

- code/messaging/src/main/java/com/adobe/marketing/mobile/aepcomposeui/aepui/state/AepCardUIState.kt
- code/messaging/src/main/java/com/adobe/marketing/mobile/aepcomposeui/aepui/state/SmallImageCardUIState.kt
- code/messaging/src/test/java/com/adobe/marketing/mobile/aepcomposeui/aepui/state/AepCardUIStateTests.kt
- code/messaging/src/test/java/com/adobe/marketing/mobile/aepcomposeui/aepui/state/SmallImageCardUIStateTests.kt
> Update AepCardUIState to be an open class, add unit tests 

- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/ContentCardSchemaDataUtils.kt
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/ContentCardUIProvider.kt
- code/messaging/src/test/java/com/adobe/marketing/mobile/messaging/ContentCardSchemaDataUtilsTest.kt
Added Unit Test cases for ContentCardUIUtils
> Added Test case for ContentCardUIUtils

- code/testapp/src/main/java/com/adobe/marketing/mobile/messagingsample/ScrollingFeedActivity.kt
> update test app to use new API name

- Documentation/sources/propositions/proposition.md
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/EdgePersonalizationResponseHandler.java
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/MessagingConstants.java
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/ParsedPropositions.java
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/Proposition.java
- code/messaging/src/test/java/com/adobe/marketing/mobile/messaging/ParsedPropositionsTests.java
- code/messaging/src/test/java/com/adobe/marketing/mobile/messaging/PropositionTests.java
- code/messaging/src/test/resources/inappPropositionV2-prio-100.json
- code/messaging/src/test/resources/inappPropositionV2-prio-20.json
- code/messaging/src/test/resources/inappPropositionV2-prio-60.json
- code/messaging/src/test/resources/inappPropositionV2.json
- code/messagingtestutils/src/main/java/com/adobe/marketing/mobile/messaging/MessagingTestUtils.java
> MOB-22249 and MOB-22214 - use rank and expose priority for proposition ordering

- .github/workflows/functional-test.yml
- Makefile
> run e2e functional tests only on scheduled test runs

- code/gradle.properties
- code/messaging/src/phone/java/com/adobe/marketing/mobile/Messaging.java
> bump version to 3.3.0-beta2

- code/messaging/src/main/java/com/adobe/marketing/mobile/aepcomposeui/utils/UIUtils.kt
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/ContentCardMapper.kt
Created extension function to fetch the meta data of small image template.
> Create extension function to get the meta data

- code/gradle.properties
- code/messaging/src/phone/java/com/adobe/marketing/mobile/Messaging.java
- code/messaging/src/test/java/com/adobe/marketing/mobile/aepcomposeui/components/SmallImageCardTests.kt
> Bumped Version to 3.3.0-beta3

- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/ContentCardAepUIExtensions.kt
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/ContentCardMapper.kt
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/ContentCardSchemaData.java
- code/messaging/src/test/java/com/adobe/marketing/mobile/aepcomposeui/SmallImageUITests.kt
> MOB-22692: Add support for AepUI custom interaction tracking

- code/gradle.properties
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/ContentCardAepUIExtensions.kt
- code/messaging/src/phone/java/com/adobe/marketing/mobile/Messaging.java
- code/messaging/src/test/java/com/adobe/marketing/mobile/aepcomposeui/SmallImageUITests.kt
> Remove custom interaction tracking api

- code/build.gradle.kts
- code/messaging/build.gradle.kts
- Lower Material 3 version to minimum required to avoid conflicts with customer app version.
- Replace Robolectric and Mockk to be used from AEP Commons library
> Lower Material3 version to minimum required

- code/messaging/src/main/java/com/adobe/marketing/mobile/MessagingPushPayload.java
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/CompletionHandler.java
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/EdgePersonalizationResponseHandler.java
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/MessagingConstants.java
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/MessagingExtension.java
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/MessagingPushBuilder.java
- code/messaging/src/phone/java/com/adobe/marketing/mobile/Messaging.java
- code/messaging/src/test/java/com/adobe/marketing/mobile/MessagingTests.java
- code/testapp/src/main/java/com/adobe/marketing/mobile/messagingsample/NotificationService.kt
- [MOB-22211] Add overloaded updatePropositions API that allows for completion. Push to in-app implementation complete and manually tested.
> [MOB-22211] Add overloaded updatePropositions API that allows for completion. Push to in-app implementation complete and manually tested.

- Documentation/sources/push-notification/how-to-display-iam-on-push-click.md
> change push to IAM java examples

- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/MessagingConstants.java
> re-add extension version constant to MessagingConstants to resolve release script error

- .github/workflows/maven-release.yml
- .github/workflows/update-version.yml
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/MessagingConstants.java
> remove extension version from MessagingConstants, update scripts

- code/gradle.properties
- code/messaging/src/main/AndroidManifest.xml
- code/messaging/src/phone/java/com/adobe/marketing/mobile/Messaging.java
> (Messaging 3.3.1) Added support for the new MobileCore.initialize API introduced in Core

- .github/workflows/functional-test.yml
> pre start AVD before running tests

- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/ContentCardUIProvider.kt
> Fix content card UI provider logging error

- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/MessagingConstants.java
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/PresentableMessageMapper.java
- code/messaging/src/test/java/com/adobe/marketing/mobile/messaging/PresentableMessageMapperTests.java
> [MOB-22892] Fit to content added to PresentableMessageMapper.java

- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/PresentableMessageMapper.java
> change fit to content builder setting based on new core changes

- code/gradle.properties
- code/messaging/build.gradle.kts
- code/messagingtestutils/build.gradle.kts
- code/testapp/build.gradle.kts
> bump aepsdk core version to 3.4.0

- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/InternalMessagingUtils.java
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/MessagingConstants.java
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/MessagingExtension.java
- code/messaging/src/test/java/com/adobe/marketing/mobile/messaging/InternalMessagingUtilsTests.java
- code/messaging/src/test/java/com/adobe/marketing/mobile/messaging/MessagingExtensionTests.java
- code/testapp/src/main/java/com/adobe/marketing/mobile/messagingsample/MainActivity.kt
- code/testapp/src/main/java/com/adobe/marketing/mobile/messagingsample/MessagingApplication.kt
- code/testapp/src/main/res/layout/activity_main.xml
> Update push force sync configuration key name and logic

- code/messaging/src/main/java/com/adobe/marketing/mobile/Message.java
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/PresentableMessageMapper.java
> Mark Message.getMetadata() as Non-Null

- code/messaging/src/main/java/com/adobe/marketing/mobile/aepcomposeui/components/AepAsyncImage.kt
- code/messaging/src/main/java/com/adobe/marketing/mobile/aepcomposeui/components/ImageOnlyCard.kt
- code/messaging/src/main/java/com/adobe/marketing/mobile/aepcomposeui/state/ImageOnlyCardUIState.kt
- code/messaging/src/main/java/com/adobe/marketing/mobile/aepcomposeui/style/ImageOnlyUIStyle.kt
- code/messaging/src/main/java/com/adobe/marketing/mobile/aepcomposeui/style/LargeImageUIStyle.kt
- code/messaging/src/main/java/com/adobe/marketing/mobile/aepcomposeui/uimodels/AepUITemplateType.kt
- code/messaging/src/main/java/com/adobe/marketing/mobile/aepcomposeui/uimodels/ImageOnlyTemplate.kt
- code/messaging/src/main/java/com/adobe/marketing/mobile/aepcomposeui/uimodels/LargeImageTemplate.kt
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/ContentCardSchemaDataUtils.kt
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/MessagingEventHandler.kt
> Fix Javadocs for Large image and image only card classes

- code/messaging/src/androidTest/java/com/adobe/marketing/mobile/messaging/E2EFunctionalTests.java
> fix format issues

- code/gradle.properties
- code/messaging/src/main/AndroidManifest.xml
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/MessagingFileProvider.kt
- code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/MessagingPushUtils.java
- code/messaging/src/phone/java/com/adobe/marketing/mobile/Messaging.java
- code/testapp/src/main/java/com/adobe/marketing/mobile/messagingsample/NotificationService.kt
Resolves a manifest merge issue seen with a customer app as they were also using the default Android provided FileProvider. 
https://jira.corp.adobe.com/browse/MOB-23991
- I added the Android provided FileProvider to the test app manifest and observed there was a manifest merge error when building the app. Verified that the app built without issues after adding the MessagingFileProvider.
- Verified that rich push gifs were still working as expected after switching to the MessagingFileProvider.
> MOB-23991: Add a Messaging extension defined FileProvider

- code/messaging/src/androidTest/java/com/adobe/marketing/mobile/messaging/E2EFunctionalTests.java
> Updating feature/inbox branch with changes in main
