adobe/aepsdk-messaging-android

README.md
code/app/build.gradle
code/gradle.properties
code/messaging/src/androidTest/java/com/adobe/marketing/mobile/PushTokenSyncingTests.java
code/messaging/src/androidTest/java/com/adobe/marketing/mobile/TestConstants.java
code/messaging/src/phone/java/com/adobe/marketing/mobile/MessagingConstant.java
code/messaging/src/phone/java/com/adobe/marketing/mobile/MessagingInternal.java
code/messaging/src/test/java/com/adobe/marketing/mobile/MessagingInternalTests.java

On every MobileCore.setPushIdentifier API call, which dispatches Generic Request Identity event is listened by Messaging extension.
Now the push identifier is extracted and shared in Messaging extension's shared state
StateStateDetails
{
"pushidentifier" : '<push_token>"
}
This shared state in read by Assurance extension, which forwards the data to Griffon session for populating the PushDebugger plugin
Note
Pushtoken is shared in shared state regardless of the ability of Messaging extension to sync the token with the edge network

[MOB-14404] Adding push token to the shared state

---

code/messaging/src/androidTest/java/com/adobe/marketing/mobile/E2EFunctionalTests.java
code/messaging/src/phone/java/com/adobe/marketing/mobile/MessagingDelegate.java
code/messaging/src/test/java/com/adobe/marketing/mobile/MessagingDelegateTests.java

When a custom messaging delegate is not set message.dismiss() was being called twice which was causing a crash to occur on the second call. to resolve it, all message dismissal will be handled via message.overrideUrlLoad to ensure one call per message dismissal is made.

[MOB-16614] fix a crash by preventing an additional message.dismiss from being called

---

code/messaging/src/phone/java/com/adobe/marketing/mobile/Message.java
code/messaging/src/test/java/com/adobe/marketing/mobile/MessageTests.java
code/messaging/src/test/java/com/adobe/marketing/mobile/MessagingInternalHandleRulesResponseContentTests.java

- a message fragment shouldn't be created if the MesagingDelegate states that messages shouldn't be shown
- cleanup some unit tests + fix a custom message delegate test

fix fragment creation issue

---

code/messaging/src/main/java/com/adobe/marketing/mobile/Message.java
code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/internal/InternalMessage.java
code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/internal/MessagingExtension.java

- Provide a default implementation for getAutoTrack() in the Message interface as it was previously present in the now internal InternalMessage class.
- also fix logging bug in MessagingExtension

provide default implementation for Message.getAutoTrack()

---

code/app/build.gradle
code/gradle.properties
code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/internal/MessagingFullscreenMessageDelegate.java
code/messaging/src/test/java/com/adobe/marketing/mobile/messaging/internal/MessagingFullscreenMessageDelegateTests.java

- `URLDecoder.decode` method is not happy when an null/empty query parameters are passed to be decoded
- Fix adds a null check and act accordingly

[MOB-18622] - Handle IAM Click URl without deeplink gracefully

---

code/app/src/main/java/com/adobe/marketing/mobile/messagingsample/MainActivity.kt
code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/internal/InternalMessage.java
code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/internal/MessagingFullscreenMessageDelegate.java
code/messaging/src/test/java/com/adobe/marketing/mobile/messaging/internal/InternalMessageTests.java
code/messaging/src/test/java/com/adobe/marketing/mobile/messaging/internal/MessagingFullscreenMessageDelegateTests.java

Display tracking was incorrectly being done before the in-app message was actually displayed. Move the display tracking to MessagingFullscreenMessageDelegate.onShow to ensure that a message is actually displayed before display tracking is done.

Fix display tracking accuracy

---

code/messaging/src/androidTest/java/com/adobe/marketing/mobile/messaging/internal/MessagingPublicAPITests.java
code/messaging/src/main/java/com/adobe/marketing/mobile/MessagingPushTrackingStatus.java
code/messaging/src/main/java/com/adobe/marketing/mobile/PushTrackingStatus.java
code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/internal/MessagingConstants.java
code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/internal/MessagingExtension.java
code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/internal/MessagingUtils.java
code/messaging/src/phone/java/com/adobe/marketing/mobile/Messaging.java
code/messaging/src/test/java/com/adobe/marketing/mobile/MessagingTests.java
code/messaging/src/test/java/com/adobe/marketing/mobile/messaging/internal/MessagingExtensionTests.java

Two changes are made to handleNotificationResponse API
- The API stops processing the notification response. If no tracking key "_xdm" is found in the notification response.
- handleNotificationResponse takes in a callback that returns enum PushTrackingStatus
- A public enum PushTrackingStaus is introduced with the following values
* TRACKING_INITIATED               - Returned when all the required data are available and the tracking has been initiated by Messaging Extension
* NO_DATASET_CONFIGURED.     - Returned when no tracking dataset is configured for Messaging Extension
* NO_TRACKING_DATA                - Returned when no tracking information is found in the Notification Response
* INVALID_MESSAGE_ID.            - Returned when NotificationReponse has empty/null identifier.
* …

[MOB-19375] -  HandleNotificationResponse API returns MessagingPushTrackingStatus enum

---

code/app/src/main/java/com/adobe/marketing/mobile/messagingsample/CodeBasedCardAdapter.kt
code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/InternalMessage.java
code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/MessagingPropositionItem.java
code/messaging/src/test/java/com/adobe/marketing/mobile/messaging/InternalMessageTests.java

- fix bug with extracting the consequence id as it is present in the consequence and not the consequence detail data map
- correctly handle json array proposition content

fix in-app message id extraction

---

code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/internal/MessageAssetDownloader.java

check for null connection in network call to download and cache remote assets for iam.
during app startup, core tries to initialize the Messaging extension by calling its constructor (in `MessagingExtension`).  the constructor initializes an `InAppNotificationHandler`, which kicks off downloading assets for cached messages to be used later in the app lifecycle.  the downloading happens in the `MessageAssetDownloader` class. in the situation where network service returns a null connection (an exception was thrown while trying to make the network call), the Messaging extension initialization would fail resulting in failure to register with the EventHub.
this fix will cause any failure while attempting to download an asset for an in-app message to be ignored, with no retry.  in the case …

-fix network calls for message asset downloading

---

code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/ContentCard.java
code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/EdgePersonalizationResponseHandler.java
code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/PropositionItem.java
code/messaging/src/phone/java/com/adobe/marketing/mobile/messaging/MessagingUtils.java
code/testapp/src/main/java/com/adobe/marketing/mobile/messagingsample/CodeBasedCardAdapter.kt
code/testapp/src/main/java/com/adobe/marketing/mobile/messagingsample/CodeBasedExperienceActivity.kt
code/testapp/src/main/java/com/adobe/marketing/mobile/messagingsample/FeedCardAdapter.kt
code/testapp/src/main/java/com/adobe/marketing/mobile/messagingsample/MessagingApplication.kt
code/testapp/src/main/java/com/adobe/marketing/mobile/messagingsample/ScrollingFeedActivity.kt
code/testapp/src/main/java/com/adobe/marketing/mobile/messagingsample/SingleFeedActivity.kt

1. Every time updatePropositionsForSurface is called, logic is now changed to completely replace the propositions in inMemoryPropositions with the ones returned in AEP Response Event for each corresponding surface.
2. Marked public API of `PropositionItem` class with `@Nullable` 
3. Made `Builder` in `ContentCard` package-protected
4. Changed the test app to only load CBE or Feed items based on the screen loaded.
https://jira.corp.adobe.com/browse/MOB-21212
When the content for a CBE campaign was changed server side (either manually or using ExD), the cached client side propositions would append the modified proposition while continuing to retain the old proposition with outdated content. This causes confusion on what the most current CBE content is.
Manual testing

Replace inMemoryPropositions instead of appending for every updatePropositionsForSurface call

---

code/messaging/src/main/java/com/adobe/marketing/mobile/aepcomposeui/AepUIConstants.kt
code/messaging/src/main/java/com/adobe/marketing/mobile/aepcomposeui/components/AepButtonComposable.kt
code/messaging/src/main/java/com/adobe/marketing/mobile/aepcomposeui/components/AepCardComposable.kt
code/messaging/src/main/java/com/adobe/marketing/mobile/aepcomposeui/components/AepColumnComposable.kt
code/messaging/src/main/java/com/adobe/marketing/mobile/aepcomposeui/components/AepRowComposable.kt
code/messaging/src/main/java/com/adobe/marketing/mobile/aepcomposeui/components/AepTextComposable.kt
code/messaging/src/main/java/com/adobe/marketing/mobile/aepcomposeui/components/SmallImageCard.kt
code/messaging/src/main/java/com/adobe/marketing/mobile/aepcomposeui/style/AepButtonStyle.kt
code/messaging/src/main/java/com/adobe/marketing/mobile/aepcomposeui/style/AepCardStyle.kt
code/messaging/src/main/java/com/adobe/marketing/mobile/aepcomposeui/style/AepColumnStyle.kt
code/messaging/src/main/java/com/adobe/marketing/mobile/aepcomposeui/style/AepRowStyle.kt
code/messaging/src/main/java/com/adobe/marketing/mobile/aepcomposeui/style/AepTextStyle.kt
code/messaging/src/main/java/com/adobe/marketing/mobile/aepcomposeui/style/AepUIStyle.kt
code/messaging/src/main/java/com/adobe/marketing/mobile/aepcomposeui/style/SmallImageUIStyle.kt
code/messaging/src/main/java/com/adobe/marketing/mobile/aepcomposeui/uimodels/AepDismissButton.kt

- Added `AepCardStyle`, `AepRowStyle` and `AepColumn`Style that defines client side style for card, row and column composables.
- Added card style, row style and column style for various elements in SmallImageCard to SmallImageUIStyle.
- Added AepCardComposable, AepRowComposable and AepColumnComposables accept and use AepCardStyle, AepRowStyle and AepColumnStyle respectively.
- Changed SmallImageCard to use AepCardComposable, AepRowComposable and AepColumnComposables.

SmallImageCard: Card, Rows and Columns

---

code/messaging/src/main/java/com/adobe/marketing/mobile/aepcomposeui/components/AepTextComposable.kt
code/messaging/src/main/java/com/adobe/marketing/mobile/aepcomposeui/components/SmallImageCard.kt
code/messaging/src/main/java/com/adobe/marketing/mobile/aepcomposeui/utils/UIUtils.kt
code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/MessagingEventHandler.kt
code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/SmallImageTemplateEventHandler.kt
code/testapp/build.gradle.kts
code/testapp/src/main/java/com/adobe/marketing/mobile/messagingsample/MessagingApplication.kt
code/testapp/src/main/java/com/adobe/marketing/mobile/messagingsample/ScrollingFeedActivity.kt
code/testapp/src/main/java/com/adobe/marketing/mobile/messagingsample/Theme.kt
code/testapp/src/main/res/drawable/refresh.xml
code/testapp/src/main/res/layout/activity_scrolling.xml

1. Added an `isLoading` flag to be used when image is being downloaded from the url
2. AepUiState `dismissed` is set to `true` when `UIEvent.Dismiss` is received.
3. SmallImageCard composable is recomposed on configuration changes like theme or orientation change leading to multiple `UIEvent.Display` events for a single "view". To ensure `decisioning.propositionDisplay` events are sent only on the initial composition, `displayed` is set to `true` in AepUiState after the first display. `ContentCardSchemaData.track(MessagingEdgeEventType.DISPLAY)` is only called if `displayed` is `false`
4. Updated messaging test app to use content card UI library

Changing UI state on SmallImageCard events + Test app updates

---

code/messaging/src/main/java/com/adobe/marketing/mobile/aepcomposeui/components/SmallImageCard.kt
code/testapp/src/main/java/com/adobe/marketing/mobile/messagingsample/ScrollingFeedActivity.kt

Fixing [issue](https://jira.corp.adobe.com/browse/MOB-22541) reported by Acrobat where content card button was taking up entire width of the row because of which it could not be aligned to the end of the row

Button right alignment not working fix

---

code/messaging/src/main/java/com/adobe/marketing/mobile/aepcomposeui/components/AepButtonComposable.kt
code/messaging/src/main/java/com/adobe/marketing/mobile/aepcomposeui/components/AepIconComposable.kt
code/messaging/src/main/java/com/adobe/marketing/mobile/aepcomposeui/components/AepImageComposable.kt
code/messaging/src/main/java/com/adobe/marketing/mobile/aepcomposeui/components/SmallImageCard.kt
code/messaging/src/main/java/com/adobe/marketing/mobile/aepcomposeui/style/AepButtonStyle.kt
code/messaging/src/test/java/com/adobe/marketing/mobile/aepcomposeui/components/AepButtonComposableTests.kt
code/messaging/src/test/java/com/adobe/marketing/mobile/aepcomposeui/components/SmallImageCardTests.kt
code/messaging/src/test/java/com/adobe/marketing/mobile/aepcomposeui/style/AepButtonStyleTests.kt
code/messaging/src/test/java/com/adobe/marketing/mobile/aepcomposeui/style/AepStyleValidator.kt

1. Added a new field `interactionSource` to `AepButtonStyle` to allow customizing the appearance / behavior of the button in different states.
2. Removed explicit `onClick` fields in `AepImageComposable` and `AepIconComposable`. It can be added/overridden using Modifier. This ensures that image in the SmallImageCard inherits the parent card click behavior by default.
[MOB-22770](https://jira.corp.adobe.com/browse/MOB-22770)
[MOB-22771](https://jira.corp.adobe.com/browse/MOB-22771)

Fix click behavior for button and image in SmallImageCard

---

code/gradle.properties
code/messaging/src/phone/java/com/adobe/marketing/mobile/Messaging.java
code/messaging/src/test/java/com/adobe/marketing/mobile/aepcomposeui/components/SmallImageCardTests.kt

1. Added a test to ensure adding `clickable` to dismissButtonStyle modifier does not override the default click handling.
2. Bumped version to beta6 for snapshot release

Add test for card clicking override, bump version to beta6

---

code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/MessageAssetDownloader.java
code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/MessagingPushBuilder.java
code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/MessagingPushUtils.java
code/messaging/src/test/java/com/adobe/marketing/mobile/messaging/MessageAssetDownloaderTests.java
code/messaging/src/test/java/com/adobe/marketing/mobile/messaging/MessagingPushUtilsTests.java
code/messaging/src/test/java/com/adobe/marketing/mobile/messaging/MessagingRichPushBuilderTests.kt

Refactor the gif download and caching code to wait for the download to complete before retrieving it from the cache. There was a race condition occurring if the asset was attempted to be retrieved before it was downloaded. This was caused by missing asset metadata mistakenly causing large gif media to appear to be corrupted cached assets.

Refactor gif download and caching to resolve race condition seen with large gif media

---

code/messaging/build.gradle.kts
code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/MessagingConstants.java
code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/PresentableMessageMapper.java
code/messaging/src/test/java/com/adobe/marketing/mobile/messaging/PresentableMessageMapperTests.java
code/messagingtestutils/build.gradle.kts

Reading the value of the key `maxWidth` currently sent in `mobileParameters` object the in-app proposition payload. Setting its value in `InAppMessageSettings` provided by Core SDK
https://github.com/adobe/aepsdk-core-android/pull/753

Added support for maxWidth in in-app message settings

---

code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/InternalMessagingUtils.java
code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/MessagingExtension.java
code/messaging/src/test/java/com/adobe/marketing/mobile/messaging/MessagingExtensionTests.java
code/testapp/src/main/java/com/adobe/marketing/mobile/messagingsample/MainActivity.kt
code/testapp/src/main/java/com/adobe/marketing/mobile/messagingsample/MessagingApplication.kt
code/testapp/src/main/res/layout/activity_main.xml

A new ECID is generated when the resetIdentities API is called. The Messaging extension should clear the existing push token from Messaging shared state and persistence when a resetIdentities event is received. The app developer will then be responsible for syncing the push token with the newly generated ECID.

Handle reset identities event by clearing the push token from messaging shared state and persistence

---

code/messaging/src/main/java/com/adobe/marketing/mobile/Message.java
code/messaging/src/main/java/com/adobe/marketing/mobile/messaging/PresentableMessageMapper.java
code/messaging/src/test/java/com/adobe/marketing/mobile/messaging/PresentableMessageMapperTests.java

Add Message.getMetadata() which exposes the "meta" property of the IAM proposition. The "meta" property contains the custom key/value pairs set in the IAM editor UI.
Jira: MOB-23681

Expose a IAM object's key value pairs

---

Documentation/sources/content-card-ui/public-classes/Styles/imageonlyuistyle.md
Documentation/sources/content-card-ui/public-classes/Styles/largeimageuistyle.md
code/messaging/src/main/java/com/adobe/marketing/mobile/aepcomposeui/components/AepAsyncImage.kt
code/messaging/src/main/java/com/adobe/marketing/mobile/aepcomposeui/components/AepButton.kt
code/messaging/src/main/java/com/adobe/marketing/mobile/aepcomposeui/components/AepButtonRow.kt
code/messaging/src/main/java/com/adobe/marketing/mobile/aepcomposeui/components/AepCard.kt
code/messaging/src/main/java/com/adobe/marketing/mobile/aepcomposeui/components/AepColumn.kt
code/messaging/src/main/java/com/adobe/marketing/mobile/aepcomposeui/components/AepDismissButton.kt
code/messaging/src/main/java/com/adobe/marketing/mobile/aepcomposeui/components/AepIcon.kt
code/messaging/src/main/java/com/adobe/marketing/mobile/aepcomposeui/components/AepImage.kt
code/messaging/src/main/java/com/adobe/marketing/mobile/aepcomposeui/components/AepRow.kt
code/messaging/src/main/java/com/adobe/marketing/mobile/aepcomposeui/components/AepText.kt
code/messaging/src/main/java/com/adobe/marketing/mobile/aepcomposeui/components/ImageOnlyCard.kt
code/messaging/src/main/java/com/adobe/marketing/mobile/aepcomposeui/components/LargeImageCard.kt
code/messaging/src/main/java/com/adobe/marketing/mobile/aepcomposeui/components/SmallImageCard.kt
code/messaging/src/test/java/com/adobe/marketing/mobile/aepcomposeui/components/AepAsyncImageTests.kt
code/messaging/src/test/java/com/adobe/marketing/mobile/aepcomposeui/components/AepButtonRowTests.kt
code/messaging/src/test/java/com/adobe/marketing/mobile/aepcomposeui/components/AepButtonTests.kt
code/messaging/src/test/java/com/adobe/marketing/mobile/aepcomposeui/components/AepCardTests.kt
code/messaging/src/test/java/com/adobe/marketing/mobile/aepcomposeui/components/AepColumnTests.kt
code/messaging/src/test/java/com/adobe/marketing/mobile/aepcomposeui/components/AepDismissButtonTests.kt
code/messaging/src/test/java/com/adobe/marketing/mobile/aepcomposeui/components/AepIconTests.kt
code/messaging/src/test/java/com/adobe/marketing/mobile/aepcomposeui/components/AepImageTests.kt
code/messaging/src/test/java/com/adobe/marketing/mobile/aepcomposeui/components/AepRowTests.kt
code/messaging/src/test/java/com/adobe/marketing/mobile/aepcomposeui/components/AepTextTests.kt

Renamed all internal composable classes to drop the `Composable` prefix

Rename composable classes to remove suffix
